# ^(?!.*(dev|sources)).*$
name: Build Fabric Mod

on:
  push:
    branches: [ 1.17 ]
  pull_request:
    branches: [ 1.17 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: beta
        files: ./build/libs/
